spring.application.name=ticket

spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.username=TICKETDB
spring.datasource.password=thumonvn2305
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-test-query=SELECT 1 FROM DUAL

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.show-sql=true

spring.jackson.serialization.write-dates-as-timestamps=false

# Gemini Configuration
# ========================
gemini.api.key=MY_GEMINI_API_KEY
gemini.base-url=https://generativelanguage.googleapis.com/v1beta/openai/
gemini.model=gemini-2.5-flash
gemini.max-tokens=1000
 
# ========================
# Server
# ========================
server.port=8080